-- MySQL Script generated by MySQL Workbench
-- Thu Nov 30 09:12:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema pf_web1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pf_web1` ;

-- -----------------------------------------------------
-- Schema pf_web1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pf_web1` DEFAULT CHARACTER SET utf8mb3 ;
SHOW WARNINGS;
USE `pf_web1` ;

-- -----------------------------------------------------
-- Table `pf_web1`.`tb_carro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_web1`.`tb_carro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pf_web1`.`tb_carro` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `modelo` VARCHAR(26) NOT NULL,
                                                    `marca` VARCHAR(26) NOT NULL,
                                                    `ano` VARCHAR(4) NOT NULL,
                                                    `placa` VARCHAR(8) NOT NULL,
                                                    PRIMARY KEY (`id`),
                                                    UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pf_web1`.`tb_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_web1`.`tb_cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pf_web1`.`tb_cliente` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `nome` VARCHAR(44) NOT NULL,
                                                      `endereco` VARCHAR(62) NOT NULL,
                                                      `telefone` VARCHAR(17) NOT NULL,
                                                      PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pf_web1`.`tb_funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_web1`.`tb_funcionario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pf_web1`.`tb_funcionario` (
                                                          `id` INT NOT NULL AUTO_INCREMENT,
                                                          `nome` VARCHAR(44) NOT NULL,
                                                          `login` VARCHAR(35) NOT NULL,
                                                          `senha` VARCHAR(44) NOT NULL,
                                                          PRIMARY KEY (`id`),
                                                          UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 2
    DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pf_web1`.`tb_os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_web1`.`tb_os` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pf_web1`.`tb_os` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `data_entrada` DATE NOT NULL,
                                                 `data_saida` DATE NULL DEFAULT NULL,
                                                 `desc_servico` VARCHAR(80) NOT NULL,
                                                 `valor_servico` DECIMAL(10,0) NOT NULL,
                                                 `valor_total` DECIMAL(10,0) NOT NULL,
                                                 `tb_carro_id` INT NOT NULL,
                                                 `tb_cliente_id` INT NOT NULL,
                                                 PRIMARY KEY (`id`),
                                                 INDEX `fk_tb_os_tb_carro_idx` (`tb_carro_id` ASC) VISIBLE,
                                                 INDEX `fk_tb_os_tb_cliente1_idx` (`tb_cliente_id` ASC) VISIBLE,
                                                 CONSTRAINT `fk_tb_os_tb_carro`
                                                     FOREIGN KEY (`tb_carro_id`)
                                                         REFERENCES `pf_web1`.`tb_carro` (`id`),
                                                 CONSTRAINT `fk_tb_os_tb_cliente1`
                                                     FOREIGN KEY (`tb_cliente_id`)
                                                         REFERENCES `pf_web1`.`tb_cliente` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pf_web1`.`tb_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_web1`.`tb_servico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pf_web1`.`tb_servico` (
                                                      `id` INT NOT NULL,
                                                      `nome` VARCHAR(44) NOT NULL,
                                                      `descricao` VARCHAR(107) NOT NULL,
                                                      `valor` DECIMAL(10,0) NOT NULL,
                                                      PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pf_web1`.`tb_servico_has_tb_os`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_web1`.`tb_servico_has_tb_os` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pf_web1`.`tb_servico_has_tb_os` (
                                                                `tb_servico_id` INT NOT NULL,
                                                                `tb_os_id` INT NOT NULL,
                                                                PRIMARY KEY (`tb_servico_id`, `tb_os_id`),
                                                                INDEX `fk_tb_servico_has_tb_os_tb_os1_idx` (`tb_os_id` ASC) VISIBLE,
                                                                INDEX `fk_tb_servico_has_tb_os_tb_servico1_idx` (`tb_servico_id` ASC) VISIBLE,
                                                                CONSTRAINT `fk_tb_servico_has_tb_os_tb_servico1`
                                                                    FOREIGN KEY (`tb_servico_id`)
                                                                        REFERENCES `pf_web1`.`tb_servico` (`id`)
                                                                        ON DELETE NO ACTION
                                                                        ON UPDATE NO ACTION,
                                                                CONSTRAINT `fk_tb_servico_has_tb_os_tb_os1`
                                                                    FOREIGN KEY (`tb_os_id`)
                                                                        REFERENCES `pf_web1`.`tb_os` (`id`)
                                                                        ON DELETE NO ACTION
                                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;

SHOW WARNINGS;